name: flutter_html_view_example
description: Demonstrates how to use the flutter_html_view plugin.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_html_view:
    path: ../

flutter:
  uses-material-design: true
